name = "megaeth-gas-price-oracle"
version = "<%= package.version %>"
description = "MegaETH Gas Price Oracle Node"

[contract.MegaEthGasPriceOracle]
artifact = "contracts/MegaEthGasPriceOracle.sol:MegaEthGasPriceOracle"
create2 = true
