// Derives cannonfile.test.foundry.toml from cannonfile.test.toml.
//
// The two stands deploy the same package. The Hardhat stand imports the core from the local
// Cannon registry (a state dump Anvil loads); a Foundry script written with
// `cannon:build --write-script` carries only the steps of its own package, so for Foundry the
// core is cloned instead — then the script deploys it too. Everything else stays byte-identical,
// which is the point: there is one description of the deploy.
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'cannonfile.test.toml';
const TARGET = 'cannonfile.test.foundry.toml';

function replaceOnce(text: string, from: string, to: string): string {
  const first = text.indexOf(from);
  if (first === -1 || text.indexOf(from, first + 1) !== -1) {
    throw new Error(`expected exactly one "${from.trim()}" in ${SOURCE}`);
  }
  return text.replace(from, to);
}

let toml = readFileSync(SOURCE, 'utf8');
// A different package name, so the clone build does not overwrite the Hardhat testable
// package in the local registry. Cannon names the cloned core's preset `with-<name>` and caps
// presets at 24 characters, hence the short name.
toml = replaceOnce(toml, 'name = "synthetix-perps-market"\n', 'name = "snx-perps-foundry"\n');
toml = replaceOnce(toml, '[import.synthetix]\n', '[clone.synthetix]\n');

const header =
  `# GENERATED by scripts/foundry-cannonfile.ts from ${SOURCE} — do not edit, do not commit.\n` +
  '# The core is cloned, not imported, so that `cannon:build --write-script` writes it into\n' +
  '# script/Deploy.sol as well.\n\n';
writeFileSync(TARGET, header + toml);
console.log(`wrote ${TARGET}`);
