name: cannon-update

on:
  workflow_dispatch:
    inputs:
      cannon_tag:
        description: "Cannon Tag"
        required: true
        default: latest
        type: choice
        options:
          - latest
          - hotfix
          - alpha

jobs:
  cannon-update:
    runs-on: self-hosted
    env:
      GT_READ: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: liqcx/tooling/.github/actions/setup-liqcx@v1

      - run: pnpm install --frozen-lockfile
      - run: pnpm cannon:${{ inputs.cannon_tag }}

      - uses: peter-evans/create-pull-request@v7
        with:
          title: "Cannon Update: ${{ inputs.cannon_tag }}"
          commit-message: "Cannon Update: ${{ inputs.cannon_tag }}"
          body: ""
          branch: cannon-${{ inputs.cannon_tag }}
          labels: dependabot, cannon
          draft: true
          add-paths: .
